#  ***** BEGIN LICENSE BLOCK *****
#  Version: MPL 1.1/GPL 2.0/LGPL 2.1
#  
#  The contents of this file are subject to the Mozilla Public License Version 
#  1.1 (the "License"); you may not use this file except in compliance with 
#  the License. You may obtain a copy of the License at 
#  http://www.mozilla.org/MPL/
#  
#  Software distributed under the License is distributed on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, either express or implied. See the License
#  for the specific language governing rights and limitations under the
#  License.
#  
#  The Original Code is the Public Suffix List.
#  
#  The Initial Developer of the Original Code is
#  Jo Hermans <jo.hermans@gmail.com>.
#  Portions created by the Initial Developer are Copyright (C) 2007
#  the Initial Developer. All Rights Reserved.
#  
#  Contributor(s):
#    Ruben Arakelyan <ruben@wackomenace.co.uk>
#    Gervase Markham <gerv@gerv.net>
#    Pamela Greene <pamg.bugs@gmail.com>
#    David Triendl <david@triendl.name>
#    The kind representatives of many TLD registries
#  
#  Alternatively, the contents of this file may be used under the terms of
#  either the GNU General Public License Version 2 or later (the "GPL"), or
#  the GNU Lesser General Public License Version 2.1 or later (the "LGPL"),
#  in which case the provisions of the GPL or the LGPL are applicable instead
#  of those above. If you wish to allow use of your version of this file only
#  under the terms of either the GPL or the LGPL, and not to allow others to
#  use your version of this file under the terms of the MPL, indicate your
#  decision by deleting the provisions above and replace them with the notice
#  and other provisions required by the GPL or the LGPL. If you do not delete
#  the provisions above, a recipient may use your version of this file under
#  the terms of any one of the MPL, the GPL or the LGPL.
#  
#  ***** END LICENSE BLOCK *****

module EffectiveTLDs
TldTree = {'ac' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
'ad' => {'nom' => {}},
'ae' => {'ac' => {},
'co' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {},
'sch' => {}},
'aero' => {'accident-investigation' => {},
'accident-prevention' => {},
'aerobatic' => {},
'aeroclub' => {},
'aerodrome' => {},
'agents' => {},
'air-surveillance' => {},
'air-traffic-control' => {},
'aircraft' => {},
'airline' => {},
'airport' => {},
'airtraffic' => {},
'ambulance' => {},
'amusement' => {},
'association' => {},
'author' => {},
'ballooning' => {},
'broker' => {},
'caa' => {},
'cargo' => {},
'catering' => {},
'certification' => {},
'championship' => {},
'charter' => {},
'civilaviation' => {},
'club' => {},
'conference' => {},
'consultant' => {},
'consulting' => {},
'control' => {},
'council' => {},
'crew' => {},
'design' => {},
'dgca' => {},
'educator' => {},
'emergency' => {},
'engine' => {},
'engineer' => {},
'entertainment' => {},
'equipment' => {},
'exchange' => {},
'express' => {},
'federation' => {},
'flight' => {},
'freight' => {},
'fuel' => {},
'gliding' => {},
'government' => {},
'groundhandling' => {},
'group' => {},
'hanggliding' => {},
'homebuilt' => {},
'insurance' => {},
'journal' => {},
'journalist' => {},
'leasing' => {},
'logistics' => {},
'magazine' => {},
'maintenance' => {},
'marketplace' => {},
'media' => {},
'microlight' => {},
'modelling' => {},
'navigation' => {},
'parachuting' => {},
'paragliding' => {},
'passenger-association' => {},
'pilot' => {},
'press' => {},
'production' => {},
'recreation' => {},
'repbody' => {},
'res' => {},
'research' => {},
'rotorcraft' => {},
'safety' => {},
'scientist' => {},
'services' => {},
'show' => {},
'skydiving' => {},
'software' => {},
'student' => {},
'taxi' => {},
'trader' => {},
'trading' => {},
'trainer' => {},
'union' => {},
'workinggroup' => {},
'works' => {}},
'af' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'ag' => {'co' => {},
'com' => {},
'net' => {},
'nom' => {},
'org' => {}},
'ai' => {'com' => {},
'net' => {},
'off' => {},
'org' => {}},
'al' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
'am' => {},
'an' => {'com' => {},
'edu' => {},
'net' => {},
'org' => {}},
'ao' => {'co' => {},
'ed' => {},
'gv' => {},
'it' => {},
'og' => {},
'pb' => {}},
'aq' => {},
'ar' => {'*' => {},
'congresodelalengua3' => {'!' => {}},
'educ' => {'!' => {}},
'gobiernoelectronico' => {'!' => {}},
'mecon' => {'!' => {}},
'nacion' => {'!' => {}},
'nic' => {'!' => {}},
'promocion' => {'!' => {}},
'retina' => {'!' => {}},
'uba' => {'!' => {}}},
'arpa' => {'e164' => {},
'in-addr' => {},
'ip6' => {},
'iris' => {},
'uri' => {},
'urn' => {}},
'as' => {'gov' => {}},
'asia' => {},
'at' => {'ac' => {},
'biz' => {},
'co' => {},
'gv' => {},
'info' => {},
'or' => {},
'priv' => {}},
'au' => {'*' => {},
'act' => {},
'edu' => {'act' => {},
'nsw' => {},
'nt' => {},
'qld' => {},
'sa' => {},
'tas' => {},
'vic' => {},
'wa' => {}},
'gov' => {'act' => {},
'nt' => {},
'qld' => {},
'sa' => {},
'tas' => {},
'vic' => {},
'wa' => {}},
'nsw' => {},
'nt' => {},
'qld' => {},
'sa' => {},
'tas' => {},
'vic' => {},
'wa' => {}},
'aw' => {'com' => {}},
'ax' => {},
'az' => {'biz' => {},
'com' => {},
'edu' => {},
'gov' => {},
'info' => {},
'int' => {},
'mil' => {},
'name' => {},
'net' => {},
'org' => {},
'pp' => {},
'pro' => {}},
'ba' => {'co' => {},
'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {},
'rs' => {},
'unbi' => {},
'unsa' => {}},
'bb' => {'biz' => {},
'com' => {},
'edu' => {},
'gov' => {},
'info' => {},
'net' => {},
'org' => {},
'store' => {}},
'bd' => {'*' => {}},
'be' => {'ac' => {}},
'bf' => {'gov' => {}},
'bg' => {'0' => {},
'1' => {},
'2' => {},
'3' => {},
'4' => {},
'5' => {},
'6' => {},
'7' => {},
'8' => {},
'9' => {},
'a' => {},
'b' => {},
'c' => {},
'd' => {},
'e' => {},
'f' => {},
'g' => {},
'h' => {},
'i' => {},
'j' => {},
'k' => {},
'l' => {},
'm' => {},
'n' => {},
'o' => {},
'p' => {},
'q' => {},
'r' => {},
's' => {},
't' => {},
'u' => {},
'v' => {},
'w' => {},
'x' => {},
'y' => {},
'z' => {}},
'bh' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'bi' => {'co' => {},
'com' => {},
'edu' => {},
'or' => {},
'org' => {}},
'biz' => {},
'bj' => {'asso' => {},
'barreau' => {},
'gouv' => {}},
'bm' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'bn' => {'*' => {}},
'bo' => {'com' => {},
'edu' => {},
'gob' => {},
'gov' => {},
'int' => {},
'mil' => {},
'net' => {},
'org' => {},
'tv' => {}},
'br' => {'adm' => {},
'adv' => {},
'agr' => {},
'am' => {},
'arq' => {},
'art' => {},
'ato' => {},
'bio' => {},
'blog' => {},
'bmd' => {},
'can' => {},
'cim' => {},
'cng' => {},
'cnt' => {},
'com' => {},
'coop' => {},
'ecn' => {},
'edu' => {},
'eng' => {},
'esp' => {},
'etc' => {},
'eti' => {},
'far' => {},
'flog' => {},
'fm' => {},
'fnd' => {},
'fot' => {},
'fst' => {},
'g12' => {},
'ggf' => {},
'gov' => {},
'imb' => {},
'ind' => {},
'inf' => {},
'jor' => {},
'jus' => {},
'lel' => {},
'mat' => {},
'med' => {},
'mil' => {},
'mus' => {},
'net' => {},
'nom' => {},
'not' => {},
'ntr' => {},
'odo' => {},
'org' => {},
'ppg' => {},
'pro' => {},
'psc' => {},
'psi' => {},
'qsl' => {},
'rec' => {},
'slg' => {},
'srv' => {},
'tmp' => {},
'trd' => {},
'tur' => {},
'tv' => {},
'vet' => {},
'vlog' => {},
'wiki' => {},
'zlg' => {}},
'bs' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'bt' => {'*' => {}},
'bw' => {'co' => {},
'org' => {}},
'by' => {'com' => {},
'gov' => {},
'mil' => {},
'of' => {}},
'bz' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'ca' => {'ab' => {},
'bc' => {},
'gc' => {},
'mb' => {},
'nb' => {},
'nf' => {},
'nl' => {},
'ns' => {},
'nt' => {},
'nu' => {},
'on' => {},
'pe' => {},
'qc' => {},
'sk' => {},
'yk' => {}},
'cat' => {},
'cc' => {},
'cd' => {'gov' => {}},
'cf' => {},
'cg' => {},
'ch' => {},
'ci' => {'ac' => {},
'asso' => {},
'aéroport' => {},
'co' => {},
'com' => {},
'ed' => {},
'edu' => {},
'go' => {},
'gouv' => {},
'int' => {},
'md' => {},
'net' => {},
'or' => {},
'org' => {},
'presse' => {}},
'ck' => {'*' => {}},
'cl' => {'gob' => {},
'gov' => {}},
'cm' => {'gov' => {}},
'cn' => {'ac' => {},
'ah' => {},
'bj' => {},
'com' => {},
'cq' => {},
'edu' => {},
'fj' => {},
'gd' => {},
'gov' => {},
'gs' => {},
'gx' => {},
'gz' => {},
'ha' => {},
'hb' => {},
'he' => {},
'hi' => {},
'hk' => {},
'hl' => {},
'hn' => {},
'jl' => {},
'js' => {},
'jx' => {},
'ln' => {},
'mil' => {},
'mo' => {},
'net' => {},
'nm' => {},
'nx' => {},
'org' => {},
'qh' => {},
'sc' => {},
'sd' => {},
'sh' => {},
'sn' => {},
'sx' => {},
'tj' => {},
'tw' => {},
'xj' => {},
'xz' => {},
'yn' => {},
'zj' => {},
'公司' => {},
'網絡' => {},
'网络' => {}},
'co' => {'arts' => {},
'com' => {},
'edu' => {},
'firm' => {},
'gov' => {},
'info' => {},
'int' => {},
'mil' => {},
'net' => {},
'nom' => {},
'org' => {},
'rec' => {},
'web' => {}},
'com' => {'ar' => {},
'br' => {},
'cn' => {},
'de' => {},
'eu' => {},
'gb' => {},
'hu' => {},
'jpn' => {},
'kr' => {},
'no' => {},
'operaunite' => {},
'qc' => {},
'ru' => {},
'sa' => {},
'se' => {},
'uk' => {},
'us' => {},
'uy' => {},
'za' => {}},
'coop' => {},
'cr' => {'ac' => {},
'co' => {},
'ed' => {},
'fi' => {},
'go' => {},
'or' => {},
'sa' => {}},
'cu' => {'com' => {},
'edu' => {},
'gov' => {},
'inf' => {},
'net' => {},
'org' => {}},
'cv' => {},
'cx' => {'gov' => {}},
'cy' => {'*' => {}},
'cz' => {},
'de' => {},
'dj' => {},
'dk' => {},
'dm' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'do' => {'*' => {}},
'dz' => {'art' => {},
'asso' => {},
'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {},
'pol' => {}},
'ec' => {'com' => {},
'edu' => {},
'fin' => {},
'gov' => {},
'info' => {},
'k12' => {},
'med' => {},
'mil' => {},
'net' => {},
'org' => {},
'pro' => {}},
'edu' => {},
'ee' => {'aip' => {},
'com' => {},
'edu' => {},
'fie' => {},
'gov' => {},
'lib' => {},
'med' => {},
'org' => {},
'pri' => {},
'riik' => {}},
'eg' => {'*' => {}},
'er' => {'*' => {}},
'es' => {'com' => {},
'edu' => {},
'gob' => {},
'nom' => {},
'org' => {}},
'et' => {'*' => {}},
'eu' => {},
'fi' => {'aland' => {},
'iki' => {}},
'fj' => {'*' => {}},
'fk' => {'*' => {}},
'fm' => {},
'fo' => {},
'fr' => {'aeroport' => {},
'assedic' => {},
'asso' => {},
'avocat' => {},
'avoues' => {},
'cci' => {},
'chambagri' => {},
'chirurgiens-dentistes' => {},
'com' => {},
'experts-comptables' => {},
'geometre-expert' => {},
'gouv' => {},
'greta' => {},
'huissier-justice' => {},
'medecin' => {},
'nom' => {},
'notaires' => {},
'pharmacien' => {},
'port' => {},
'prd' => {},
'presse' => {},
'tm' => {},
'veterinaire' => {}},
'ga' => {},
'gd' => {},
'ge' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {},
'pvt' => {}},
'gf' => {},
'gg' => {'co' => {},
'gov' => {},
'net' => {},
'org' => {},
'sch' => {}},
'gh' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'org' => {}},
'gi' => {'com' => {},
'edu' => {},
'gov' => {},
'ltd' => {},
'mod' => {},
'org' => {}},
'gl' => {},
'gm' => {},
'gn' => {'ac' => {},
'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'gov' => {},
'gp' => {'asso' => {},
'com' => {},
'edu' => {},
'mobi' => {},
'net' => {},
'org' => {}},
'gq' => {},
'gr' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'gs' => {},
'gt' => {'*' => {}},
'gu' => {'*' => {}},
'gw' => {},
'gy' => {'co' => {},
'com' => {},
'net' => {}},
'hk' => {'com' => {},
'edu' => {},
'gov' => {},
'idv' => {},
'net' => {},
'org' => {},
'个人' => {},
'個人' => {},
'公司' => {},
'政府' => {},
'敎育' => {},
'教育' => {},
'箇人' => {},
'組織' => {},
'組织' => {},
'網絡' => {},
'網络' => {},
'组織' => {},
'组织' => {},
'网絡' => {},
'网络' => {}},
'hm' => {},
'hn' => {'com' => {},
'edu' => {},
'gob' => {},
'mil' => {},
'net' => {},
'org' => {}},
'hr' => {'com' => {},
'from' => {},
'iz' => {},
'name' => {}},
'ht' => {'adult' => {},
'art' => {},
'asso' => {},
'com' => {},
'coop' => {},
'edu' => {},
'firm' => {},
'gouv' => {},
'info' => {},
'med' => {},
'net' => {},
'org' => {},
'perso' => {},
'pol' => {},
'pro' => {},
'rel' => {},
'shop' => {}},
'hu' => {'2000' => {},
'agrar' => {},
'bolt' => {},
'casino' => {},
'city' => {},
'co' => {},
'erotica' => {},
'erotika' => {},
'film' => {},
'forum' => {},
'games' => {},
'hotel' => {},
'info' => {},
'ingatlan' => {},
'jogasz' => {},
'konyvelo' => {},
'lakas' => {},
'media' => {},
'news' => {},
'org' => {},
'priv' => {},
'reklam' => {},
'sex' => {},
'shop' => {},
'sport' => {},
'suli' => {},
'szex' => {},
'tm' => {},
'tozsde' => {},
'utazas' => {},
'video' => {}},
'id' => {'*' => {}},
'ie' => {'gov' => {}},
'il' => {'*' => {}},
'im' => {'ac' => {},
'co' => {'ltd' => {},
'plc' => {}},
'gov' => {},
'net' => {},
'nic' => {},
'org' => {}},
'in' => {'ac' => {},
'co' => {},
'edu' => {},
'firm' => {},
'gen' => {},
'gov' => {},
'ind' => {},
'mil' => {},
'net' => {},
'nic' => {},
'org' => {},
'res' => {}},
'info' => {},
'int' => {'eu' => {}},
'io' => {'com' => {}},
'iq' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
'ir' => {'ac' => {},
'co' => {},
'gov' => {},
'id' => {},
'net' => {},
'org' => {},
'sch' => {},
'ايران' => {},
'ایران' => {}},
'is' => {'com' => {},
'edu' => {},
'gov' => {},
'int' => {},
'net' => {},
'org' => {}},
'it' => {'ag' => {},
'agrigento' => {},
'al' => {},
'alessandria' => {},
'alto-adige' => {},
'altoadige' => {},
'an' => {},
'ancona' => {},
'ao' => {},
'aosta' => {},
'aoste' => {},
'ap' => {},
'aq' => {},
'aquila' => {},
'ar' => {},
'arezzo' => {},
'ascoli-piceno' => {},
'ascolipiceno' => {},
'asti' => {},
'at' => {},
'av' => {},
'avellino' => {},
'ba' => {},
'balsan' => {},
'bari' => {},
'barletta-andria-trani' => {},
'barlettaandriatrani' => {},
'belluno' => {},
'benevento' => {},
'bergamo' => {},
'bg' => {},
'bi' => {},
'biella' => {},
'bl' => {},
'bn' => {},
'bo' => {},
'bologna' => {},
'bolzano' => {},
'bozen' => {},
'br' => {},
'brescia' => {},
'brindisi' => {},
'bs' => {},
'bz' => {},
'ca' => {},
'cagliari' => {},
'caltanissetta' => {},
'campobasso' => {},
'caserta' => {},
'catania' => {},
'catanzaro' => {},
'cb' => {},
'ce' => {},
'ch' => {},
'chieti' => {},
'cl' => {},
'cn' => {},
'co' => {},
'como' => {},
'cosenza' => {},
'cr' => {},
'cremona' => {},
'crotone' => {},
'cs' => {},
'ct' => {},
'cuneo' => {},
'cz' => {},
'edu' => {},
'en' => {},
'enna' => {},
'fc' => {},
'fe' => {},
'fermo' => {},
'ferrara' => {},
'fg' => {},
'fi' => {},
'firenze' => {},
'florence' => {},
'foggia' => {},
'forli-cesena' => {},
'forlicesena' => {},
'fr' => {},
'frosinone' => {},
'ge' => {},
'genoa' => {},
'genova' => {},
'go' => {},
'gorizia' => {},
'gov' => {},
'gr' => {},
'grosseto' => {},
'im' => {},
'imperia' => {},
'is' => {},
'isernia' => {},
'kr' => {},
'la-spezia' => {},
'laquila' => {},
'laspezia' => {},
'latina' => {},
'lc' => {},
'le' => {},
'lecce' => {},
'lecco' => {},
'li' => {},
'livorno' => {},
'lo' => {},
'lodi' => {},
'lt' => {},
'lu' => {},
'lucca' => {},
'macerata' => {},
'mantova' => {},
'massa-carrara' => {},
'massacarrara' => {},
'matera' => {},
'mc' => {},
'me' => {},
'messina' => {},
'mi' => {},
'milan' => {},
'milano' => {},
'mn' => {},
'mo' => {},
'modena' => {},
'monza' => {},
'ms' => {},
'mt' => {},
'na' => {},
'naples' => {},
'napoli' => {},
'no' => {},
'novara' => {},
'nu' => {},
'nuoro' => {},
'or' => {},
'oristano' => {},
'pa' => {},
'padova' => {},
'padua' => {},
'palermo' => {},
'parma' => {},
'pavia' => {},
'pc' => {},
'pd' => {},
'pe' => {},
'perugia' => {},
'pesaro-urbino' => {},
'pesarourbino' => {},
'pescara' => {},
'pg' => {},
'pi' => {},
'piacenza' => {},
'pisa' => {},
'pistoia' => {},
'pn' => {},
'po' => {},
'pordenone' => {},
'potenza' => {},
'pr' => {},
'prato' => {},
'pt' => {},
'pu' => {},
'pv' => {},
'pz' => {},
'ra' => {},
'ragusa' => {},
'ravenna' => {},
'rc' => {},
're' => {},
'reggio-calabria' => {},
'reggio-emilia' => {},
'reggiocalabria' => {},
'reggioemilia' => {},
'rg' => {},
'ri' => {},
'rieti' => {},
'rimini' => {},
'rm' => {},
'rn' => {},
'ro' => {},
'roma' => {},
'rome' => {},
'rovigo' => {},
'sa' => {},
'salerno' => {},
'sassari' => {},
'savona' => {},
'si' => {},
'siena' => {},
'siracusa' => {},
'so' => {},
'sondrio' => {},
'sp' => {},
'sr' => {},
'ss' => {},
'suedtirol' => {},
'sv' => {},
'ta' => {},
'taranto' => {},
'te' => {},
'teramo' => {},
'terni' => {},
'tn' => {},
'to' => {},
'torino' => {},
'tp' => {},
'tr' => {},
'trapani' => {},
'trentino' => {},
'trento' => {},
'treviso' => {},
'trieste' => {},
'ts' => {},
'turin' => {},
'tv' => {},
'ud' => {},
'udine' => {},
'va' => {},
'varese' => {},
'vb' => {},
'vc' => {},
've' => {},
'venezia' => {},
'venice' => {},
'verbania' => {},
'vercelli' => {},
'verona' => {},
'vi' => {},
'vibo-valentia' => {},
'vibovalentia' => {},
'vicenza' => {},
'viterbo' => {},
'vr' => {},
'vt' => {},
'vv' => {}},
'je' => {'co' => {},
'gov' => {},
'net' => {},
'org' => {},
'sch' => {}},
'jm' => {'*' => {}},
'jo' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'name' => {},
'net' => {},
'org' => {},
'sch' => {}},
'jobs' => {},
'jp' => {'ac' => {},
'ad' => {},
'aichi' => {'*' => {},
'pref' => {'!' => {}}},
'akita' => {'*' => {},
'pref' => {'!' => {}}},
'aomori' => {'*' => {},
'pref' => {'!' => {}}},
'chiba' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'co' => {},
'ed' => {},
'ehime' => {'*' => {},
'pref' => {'!' => {}}},
'fukui' => {'*' => {},
'pref' => {'!' => {}}},
'fukuoka' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'fukushima' => {'*' => {},
'pref' => {'!' => {}}},
'gifu' => {'*' => {},
'pref' => {'!' => {}}},
'go' => {},
'gr' => {},
'gunma' => {'*' => {},
'pref' => {'!' => {}}},
'hiroshima' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'hokkaido' => {'*' => {},
'pref' => {'!' => {}}},
'hyogo' => {'*' => {},
'pref' => {'!' => {}}},
'ibaraki' => {'*' => {},
'pref' => {'!' => {}}},
'ishikawa' => {'*' => {},
'pref' => {'!' => {}}},
'iwate' => {'*' => {},
'pref' => {'!' => {}}},
'kagawa' => {'*' => {},
'pref' => {'!' => {}}},
'kagoshima' => {'*' => {},
'pref' => {'!' => {}}},
'kanagawa' => {'*' => {},
'pref' => {'!' => {}}},
'kawasaki' => {'*' => {},
'city' => {'!' => {}}},
'kitakyushu' => {'*' => {},
'city' => {'!' => {}}},
'kobe' => {'*' => {},
'city' => {'!' => {}}},
'kochi' => {'*' => {},
'pref' => {'!' => {}}},
'kumamoto' => {'*' => {},
'pref' => {'!' => {}}},
'kyoto' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'lg' => {},
'mie' => {'*' => {},
'pref' => {'!' => {}}},
'miyagi' => {'*' => {},
'pref' => {'!' => {}}},
'miyazaki' => {'*' => {},
'pref' => {'!' => {}}},
'nagano' => {'*' => {},
'pref' => {'!' => {}}},
'nagasaki' => {'*' => {},
'pref' => {'!' => {}}},
'nagoya' => {'*' => {},
'city' => {'!' => {}}},
'nara' => {'*' => {},
'pref' => {'!' => {}}},
'ne' => {},
'niigata' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'oita' => {'*' => {},
'pref' => {'!' => {}}},
'okayama' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'okinawa' => {'*' => {},
'pref' => {'!' => {}}},
'or' => {},
'osaka' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'saga' => {'*' => {},
'pref' => {'!' => {}}},
'saitama' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'sapporo' => {'*' => {},
'city' => {'!' => {}}},
'sendai' => {'*' => {},
'city' => {'!' => {}}},
'shiga' => {'*' => {},
'pref' => {'!' => {}}},
'shimane' => {'*' => {},
'pref' => {'!' => {}}},
'shizuoka' => {'*' => {},
'city' => {'!' => {}},
'pref' => {'!' => {}}},
'tochigi' => {'*' => {},
'pref' => {'!' => {}}},
'tokushima' => {'*' => {},
'pref' => {'!' => {}}},
'tokyo' => {'*' => {},
'metro' => {'!' => {}}},
'tottori' => {'*' => {},
'pref' => {'!' => {}}},
'toyama' => {'*' => {},
'pref' => {'!' => {}}},
'wakayama' => {'*' => {},
'pref' => {'!' => {}}},
'yamagata' => {'*' => {},
'pref' => {'!' => {}}},
'yamaguchi' => {'*' => {},
'pref' => {'!' => {}}},
'yamanashi' => {'*' => {},
'pref' => {'!' => {}}},
'yokohama' => {'*' => {},
'city' => {'!' => {}}}},
'ke' => {'*' => {}},
'kg' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
'kh' => {'*' => {}},
'ki' => {'biz' => {},
'com' => {},
'edu' => {},
'gov' => {},
'info' => {},
'net' => {},
'org' => {}},
'km' => {'ass' => {},
'asso' => {},
'com' => {},
'coop' => {},
'edu' => {},
'gouv' => {},
'gov' => {},
'medecin' => {},
'mil' => {},
'nom' => {},
'notaires' => {},
'org' => {},
'pharmaciens' => {},
'prd' => {},
'presse' => {},
'tm' => {},
'veterinaire' => {}},
'kn' => {'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'kr' => {'ac' => {},
'busan' => {},
'chungbuk' => {},
'chungnam' => {},
'co' => {},
'daegu' => {},
'daejeon' => {},
'es' => {},
'gangwon' => {},
'go' => {},
'gwangju' => {},
'gyeongbuk' => {},
'gyeonggi' => {},
'gyeongnam' => {},
'hs' => {},
'incheon' => {},
'jeju' => {},
'jeonbuk' => {},
'jeonnam' => {},
'kg' => {},
'mil' => {},
'ms' => {},
'ne' => {},
'or' => {},
'pe' => {},
're' => {},
'sc' => {},
'seoul' => {},
'ulsan' => {}},
'kw' => {'*' => {}},
'ky' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'kz' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
'la' => {'c' => {},
'com' => {},
'edu' => {},
'gov' => {},
'info' => {},
'int' => {},
'net' => {},
'org' => {},
'per' => {}},
'lb' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'lc' => {'co' => {},
'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'li' => {},
'lk' => {'assn' => {},
'com' => {},
'edu' => {},
'gov' => {},
'grp' => {},
'hotel' => {},
'int' => {},
'ltd' => {},
'net' => {},
'ngo' => {},
'org' => {},
'sch' => {},
'soc' => {},
'web' => {}},
'local' => {},
'lr' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'ls' => {'co' => {},
'org' => {}},
'lt' => {'gov' => {}},
'lu' => {},
'lv' => {'asn' => {},
'com' => {},
'conf' => {},
'edu' => {},
'gov' => {},
'id' => {},
'mil' => {},
'net' => {},
'org' => {}},
'ly' => {'com' => {},
'edu' => {},
'gov' => {},
'id' => {},
'med' => {},
'net' => {},
'org' => {},
'plc' => {},
'sch' => {}},
'ma' => {'ac' => {},
'co' => {},
'gov' => {},
'net' => {},
'org' => {},
'press' => {}},
'mc' => {'asso' => {},
'tm' => {}},
'md' => {},
'me' => {'ac' => {},
'co' => {},
'edu' => {},
'gov' => {},
'its' => {},
'net' => {},
'org' => {},
'priv' => {}},
'mg' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'nom' => {},
'org' => {},
'prd' => {},
'tm' => {}},
'mh' => {},
'mil' => {},
'mk' => {'com' => {},
'edu' => {},
'gov' => {},
'inf' => {},
'name' => {},
'net' => {},
'org' => {}},
'ml' => {'com' => {},
'edu' => {},
'gouv' => {},
'gov' => {},
'net' => {},
'org' => {},
'presse' => {}},
'mm' => {'*' => {}},
'mn' => {'edu' => {},
'gov' => {},
'org' => {}},
'mo' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'mobi' => {},
'mp' => {},
'mq' => {},
'mr' => {'gov' => {}},
'ms' => {},
'mt' => {'*' => {}},
'mu' => {'ac' => {},
'co' => {},
'com' => {},
'gov' => {},
'net' => {},
'or' => {},
'org' => {}},
'museum' => {'academy' => {},
'agriculture' => {},
'air' => {},
'airguard' => {},
'alabama' => {},
'alaska' => {},
'amber' => {},
'ambulance' => {},
'american' => {},
'americana' => {},
'americanantiques' => {},
'americanart' => {},
'amsterdam' => {},
'and' => {},
'annefrank' => {},
'anthro' => {},
'anthropology' => {},
'antiques' => {},
'aquarium' => {},
'arboretum' => {},
'archaeological' => {},
'archaeology' => {},
'architecture' => {},
'art' => {},
'artanddesign' => {},
'artcenter' => {},
'artdeco' => {},
'arteducation' => {},
'artgallery' => {},
'arts' => {},
'artsandcrafts' => {},
'asmatart' => {},
'assassination' => {},
'assisi' => {},
'association' => {},
'astronomy' => {},
'atlanta' => {},
'austin' => {},
'australia' => {},
'automotive' => {},
'aviation' => {},
'axis' => {},
'badajoz' => {},
'baghdad' => {},
'bahn' => {},
'bale' => {},
'baltimore' => {},
'barcelona' => {},
'baseball' => {},
'basel' => {},
'baths' => {},
'bauern' => {},
'beauxarts' => {},
'beeldengeluid' => {},
'bellevue' => {},
'bergbau' => {},
'berkeley' => {},
'berlin' => {},
'bern' => {},
'bible' => {},
'bilbao' => {},
'bill' => {},
'birdart' => {},
'birthplace' => {},
'bonn' => {},
'boston' => {},
'botanical' => {},
'botanicalgarden' => {},
'botanicgarden' => {},
'botany' => {},
'brandywinevalley' => {},
'brasil' => {},
'bristol' => {},
'british' => {},
'britishcolumbia' => {},
'broadcast' => {},
'brunel' => {},
'brussel' => {},
'brussels' => {},
'bruxelles' => {},
'building' => {},
'burghof' => {},
'bus' => {},
'bushey' => {},
'cadaques' => {},
'california' => {},
'cambridge' => {},
'can' => {},
'canada' => {},
'capebreton' => {},
'carrier' => {},
'cartoonart' => {},
'casadelamoneda' => {},
'castle' => {},
'castres' => {},
'celtic' => {},
'center' => {},
'chattanooga' => {},
'cheltenham' => {},
'chesapeakebay' => {},
'chicago' => {},
'children' => {},
'childrens' => {},
'childrensgarden' => {},
'chiropractic' => {},
'chocolate' => {},
'christiansburg' => {},
'cincinnati' => {},
'cinema' => {},
'circus' => {},
'civilisation' => {},
'civilization' => {},
'civilwar' => {},
'clinton' => {},
'clock' => {},
'coal' => {},
'coastaldefence' => {},
'cody' => {},
'coldwar' => {},
'collection' => {},
'colonialwilliamsburg' => {},
'coloradoplateau' => {},
'columbia' => {},
'columbus' => {},
'communication' => {},
'communications' => {},
'community' => {},
'computer' => {},
'computerhistory' => {},
'comunicações' => {},
'contemporary' => {},
'contemporaryart' => {},
'convent' => {},
'copenhagen' => {},
'corporation' => {},
'correios-e-telecomunicações' => {},
'corvette' => {},
'costume' => {},
'countryestate' => {},
'county' => {},
'crafts' => {},
'cranbrook' => {},
'creation' => {},
'cultural' => {},
'culturalcenter' => {},
'culture' => {},
'cyber' => {},
'cymru' => {},
'dali' => {},
'dallas' => {},
'database' => {},
'ddr' => {},
'decorativearts' => {},
'delaware' => {},
'delmenhorst' => {},
'denmark' => {},
'depot' => {},
'design' => {},
'detroit' => {},
'dinosaur' => {},
'discovery' => {},
'dolls' => {},
'donostia' => {},
'durham' => {},
'eastafrica' => {},
'eastcoast' => {},
'education' => {},
'educational' => {},
'egyptian' => {},
'eisenbahn' => {},
'elburg' => {},
'elvendrell' => {},
'embroidery' => {},
'encyclopedic' => {},
'england' => {},
'entomology' => {},
'environment' => {},
'environmentalconservation' => {},
'epilepsy' => {},
'essex' => {},
'estate' => {},
'ethnology' => {},
'exeter' => {},
'exhibition' => {},
'family' => {},
'farm' => {},
'farmequipment' => {},
'farmers' => {},
'farmstead' => {},
'field' => {},
'figueres' => {},
'filatelia' => {},
'film' => {},
'fineart' => {},
'finearts' => {},
'finland' => {},
'flanders' => {},
'florida' => {},
'force' => {},
'fortmissoula' => {},
'fortworth' => {},
'foundation' => {},
'francaise' => {},
'frankfurt' => {},
'franziskaner' => {},
'freemasonry' => {},
'freiburg' => {},
'fribourg' => {},
'frog' => {},
'fundacio' => {},
'furniture' => {},
'gallery' => {},
'garden' => {},
'gateway' => {},
'geelvinck' => {},
'gemological' => {},
'geology' => {},
'georgia' => {},
'giessen' => {},
'glas' => {},
'glass' => {},
'gorge' => {},
'grandrapids' => {},
'graz' => {},
'guernsey' => {},
'halloffame' => {},
'hamburg' => {},
'handson' => {},
'harvestcelebration' => {},
'hawaii' => {},
'health' => {},
'heimatunduhren' => {},
'hellas' => {},
'helsinki' => {},
'hembygdsforbund' => {},
'heritage' => {},
'histoire' => {},
'historical' => {},
'historicalsociety' => {},
'historichouses' => {},
'historisch' => {},
'historisches' => {},
'history' => {},
'historyofscience' => {},
'horology' => {},
'house' => {},
'humanities' => {},
'illustration' => {},
'imageandsound' => {},
'indian' => {},
'indiana' => {},
'indianapolis' => {},
'indianmarket' => {},
'intelligence' => {},
'interactive' => {},
'iraq' => {},
'iron' => {},
'isleofman' => {},
'jamison' => {},
'jefferson' => {},
'jerusalem' => {},
'jewelry' => {},
'jewish' => {},
'jewishart' => {},
'jfk' => {},
'journalism' => {},
'judaica' => {},
'judygarland' => {},
'juedisches' => {},
'juif' => {},
'karate' => {},
'karikatur' => {},
'kids' => {},
'koebenhavn' => {},
'koeln' => {},
'kunst' => {},
'kunstsammlung' => {},
'kunstunddesign' => {},
'labor' => {},
'labour' => {},
'lajolla' => {},
'lancashire' => {},
'landes' => {},
'lans' => {},
'larsson' => {},
'lewismiller' => {},
'lincoln' => {},
'linz' => {},
'living' => {},
'livinghistory' => {},
'localhistory' => {},
'london' => {},
'losangeles' => {},
'louvre' => {},
'loyalist' => {},
'lucerne' => {},
'luxembourg' => {},
'luzern' => {},
'läns' => {},
'mad' => {},
'madrid' => {},
'mallorca' => {},
'manchester' => {},
'mansion' => {},
'mansions' => {},
'manx' => {},
'marburg' => {},
'maritime' => {},
'maritimo' => {},
'maryland' => {},
'marylhurst' => {},
'media' => {},
'medical' => {},
'medizinhistorisches' => {},
'meeres' => {},
'memorial' => {},
'mesaverde' => {},
'michigan' => {},
'midatlantic' => {},
'military' => {},
'mill' => {},
'miners' => {},
'mining' => {},
'minnesota' => {},
'missile' => {},
'missoula' => {},
'modern' => {},
'moma' => {},
'money' => {},
'monmouth' => {},
'monticello' => {},
'montreal' => {},
'moscow' => {},
'motorcycle' => {},
'muenchen' => {},
'muenster' => {},
'mulhouse' => {},
'muncie' => {},
'museet' => {},
'museumcenter' => {},
'museumvereniging' => {},
'music' => {},
'national' => {},
'nationalfirearms' => {},
'nationalheritage' => {},
'nativeamerican' => {},
'naturalhistory' => {},
'naturalhistorymuseum' => {},
'naturalsciences' => {},
'nature' => {},
'naturhistorisches' => {},
'natuurwetenschappen' => {},
'naumburg' => {},
'naval' => {},
'nebraska' => {},
'neues' => {},
'newhampshire' => {},
'newjersey' => {},
'newmexico' => {},
'newport' => {},
'newspaper' => {},
'newyork' => {},
'niepce' => {},
'norfolk' => {},
'north' => {},
'nrw' => {},
'nuernberg' => {},
'nuremberg' => {},
'nyc' => {},
'nyny' => {},
'oceanographic' => {},
'oceanographique' => {},
'omaha' => {},
'online' => {},
'ontario' => {},
'openair' => {},
'oregon' => {},
'oregontrail' => {},
'otago' => {},
'oxford' => {},
'pacific' => {},
'paderborn' => {},
'palace' => {},
'paleo' => {},
'palmsprings' => {},
'panama' => {},
'paris' => {},
'pasadena' => {},
'pharmacy' => {},
'philadelphia' => {},
'philadelphiaarea' => {},
'philately' => {},
'phoenix' => {},
'photography' => {},
'pilots' => {},
'pittsburgh' => {},
'planetarium' => {},
'plantation' => {},
'plants' => {},
'plaza' => {},
'portal' => {},
'portland' => {},
'portlligat' => {},
'posts-and-telecommunications' => {},
'preservation' => {},
'presidio' => {},
'press' => {},
'project' => {},
'public' => {},
'pubol' => {},
'quebec' => {},
'railroad' => {},
'railway' => {},
'research' => {},
'resistance' => {},
'riodejaneiro' => {},
'rochester' => {},
'rockart' => {},
'roma' => {},
'russia' => {},
'saintlouis' => {},
'salem' => {},
'salvadordali' => {},
'salzburg' => {},
'sandiego' => {},
'sanfrancisco' => {},
'santabarbara' => {},
'santacruz' => {},
'santafe' => {},
'saskatchewan' => {},
'satx' => {},
'savannahga' => {},
'schlesisches' => {},
'schoenbrunn' => {},
'schokoladen' => {},
'school' => {},
'schweiz' => {},
'science' => {},
'science-fiction' => {},
'scienceandhistory' => {},
'scienceandindustry' => {},
'sciencecenter' => {},
'sciencecenters' => {},
'sciencehistory' => {},
'sciences' => {},
'sciencesnaturelles' => {},
'scotland' => {},
'seaport' => {},
'settlement' => {},
'settlers' => {},
'shell' => {},
'sherbrooke' => {},
'sibenik' => {},
'silk' => {},
'ski' => {},
'skole' => {},
'society' => {},
'sologne' => {},
'soundandvision' => {},
'southcarolina' => {},
'southwest' => {},
'space' => {},
'spy' => {},
'square' => {},
'stadt' => {},
'stalbans' => {},
'starnberg' => {},
'state' => {},
'stateofdelaware' => {},
'station' => {},
'steam' => {},
'steiermark' => {},
'stjohn' => {},
'stockholm' => {},
'stpetersburg' => {},
'stuttgart' => {},
'suisse' => {},
'surgeonshall' => {},
'surrey' => {},
'svizzera' => {},
'sweden' => {},
'sydney' => {},
'tank' => {},
'tcm' => {},
'technology' => {},
'telekommunikation' => {},
'television' => {},
'texas' => {},
'textile' => {},
'theater' => {},
'time' => {},
'timekeeping' => {},
'topology' => {},
'torino' => {},
'touch' => {},
'town' => {},
'transport' => {},
'tree' => {},
'trolley' => {},
'trust' => {},
'trustee' => {},
'uhren' => {},
'ulm' => {},
'undersea' => {},
'university' => {},
'usa' => {},
'usantiques' => {},
'usarts' => {},
'uscountryestate' => {},
'usculture' => {},
'usdecorativearts' => {},
'usgarden' => {},
'ushistory' => {},
'ushuaia' => {},
'uslivinghistory' => {},
'utah' => {},
'uvic' => {},
'valley' => {},
'vantaa' => {},
'versailles' => {},
'viking' => {},
'village' => {},
'virginia' => {},
'virtual' => {},
'virtuel' => {},
'vlaanderen' => {},
'volkenkunde' => {},
'wales' => {},
'wallonie' => {},
'war' => {},
'washingtondc' => {},
'watch-and-clock' => {},
'watchandclock' => {},
'western' => {},
'westfalen' => {},
'whaling' => {},
'wildlife' => {},
'williamsburg' => {},
'windmill' => {},
'workshop' => {},
'york' => {},
'yorkshire' => {},
'yosemite' => {},
'youth' => {},
'zoological' => {},
'zoology' => {},
'иком' => {},
'ירושלים' => {}},
'mv' => {'aero' => {},
'biz' => {},
'com' => {},
'coop' => {},
'edu' => {},
'gov' => {},
'info' => {},
'int' => {},
'mil' => {},
'museum' => {},
'name' => {},
'net' => {},
'org' => {},
'pro' => {}},
'mw' => {'ac' => {},
'biz' => {},
'co' => {},
'com' => {},
'coop' => {},
'edu' => {},
'gov' => {},
'int' => {},
'museum' => {},
'net' => {},
'org' => {}},
'mx' => {'com' => {},
'edu' => {},
'gob' => {},
'net' => {},
'org' => {}},
'my' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'name' => {},
'net' => {},
'org' => {}},
'mz' => {'*' => {}},
'na' => {'ca' => {},
'cc' => {},
'co' => {},
'com' => {},
'dr' => {},
'in' => {},
'info' => {},
'mobi' => {},
'mx' => {},
'name' => {},
'or' => {},
'org' => {},
'pro' => {},
'school' => {},
'tv' => {},
'us' => {},
'ws' => {}},
'name' => {},
'nc' => {'asso' => {}},
'ne' => {},
'net' => {'gb' => {},
'se' => {},
'uk' => {},
'za' => {}},
'nf' => {'arts' => {},
'com' => {},
'firm' => {},
'info' => {},
'net' => {},
'other' => {},
'per' => {},
'rec' => {},
'store' => {},
'web' => {}},
'ng' => {'ac' => {},
'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'ni' => {'*' => {}},
'nl' => {},
'no' => {'aa' => {'gs' => {}},
'aarborte' => {},
'aejrie' => {},
'afjord' => {},
'agdenes' => {},
'ah' => {'gs' => {}},
'akershus' => {'nes' => {}},
'aknoluokta' => {},
'akrehamn' => {},
'al' => {},
'alaheadju' => {},
'alesund' => {},
'algard' => {},
'alstahaug' => {},
'alta' => {},
'alvdal' => {},
'amli' => {},
'amot' => {},
'andasuolo' => {},
'andebu' => {},
'andoy' => {},
'andøy' => {},
'ardal' => {},
'aremark' => {},
'arendal' => {},
'arna' => {},
'aseral' => {},
'asker' => {},
'askim' => {},
'askoy' => {},
'askvoll' => {},
'askøy' => {},
'asnes' => {},
'audnedaln' => {},
'aukra' => {},
'aure' => {},
'aurland' => {},
'aurskog-holand' => {},
'aurskog-høland' => {},
'austevoll' => {},
'austrheim' => {},
'averoy' => {},
'averøy' => {},
'badaddja' => {},
'bahcavuotna' => {},
'bahccavuotna' => {},
'baidar' => {},
'bajddar' => {},
'balat' => {},
'balestrand' => {},
'ballangen' => {},
'balsfjord' => {},
'bamble' => {},
'bardu' => {},
'barum' => {},
'batsfjord' => {},
'bearalvahki' => {},
'bearalváhki' => {},
'beardu' => {},
'beiarn' => {},
'berg' => {},
'bergen' => {},
'berlevag' => {},
'berlevåg' => {},
'bievat' => {},
'bievát' => {},
'bindal' => {},
'birkenes' => {},
'bjarkoy' => {},
'bjarkøy' => {},
'bjerkreim' => {},
'bjugn' => {},
'bodo' => {},
'bodø' => {},
'bokn' => {},
'bomlo' => {},
'bremanger' => {},
'bronnoy' => {},
'bronnoysund' => {},
'brumunddal' => {},
'bryne' => {},
'brønnøy' => {},
'brønnøysund' => {},
'bu' => {'gs' => {}},
'budejju' => {},
'buskerud' => {'nes' => {}},
'bygland' => {},
'bykle' => {},
'báhcavuotna' => {},
'báhccavuotna' => {},
'báidár' => {},
'bájddar' => {},
'bálát' => {},
'bådåddjå' => {},
'båtsfjord' => {},
'bærum' => {},
'bømlo' => {},
'cahcesuolo' => {},
'davvenjarga' => {},
'davvenjárga' => {},
'davvesiida' => {},
'deatnu' => {},
'dep' => {},
'dielddanuorri' => {},
'divtasvuodna' => {},
'divttasvuotna' => {},
'donna' => {},
'dovre' => {},
'drammen' => {},
'drangedal' => {},
'drobak' => {},
'drøbak' => {},
'dyroy' => {},
'dyrøy' => {},
'dønna' => {},
'egersund' => {},
'eid' => {},
'eidfjord' => {},
'eidsberg' => {},
'eidskog' => {},
'eidsvoll' => {},
'eigersund' => {},
'elverum' => {},
'enebakk' => {},
'engerdal' => {},
'etne' => {},
'etnedal' => {},
'evenassi' => {},
'evenes' => {},
'evenášši' => {},
'evje-og-hornnes' => {},
'farsund' => {},
'fauske' => {},
'fedje' => {},
'fet' => {},
'fetsund' => {},
'fhs' => {},
'finnoy' => {},
'finnøy' => {},
'fitjar' => {},
'fjaler' => {},
'fjell' => {},
'fla' => {},
'flakstad' => {},
'flatanger' => {},
'flekkefjord' => {},
'flesberg' => {},
'flora' => {},
'floro' => {},
'florø' => {},
'flå' => {},
'fm' => {'gs' => {}},
'folkebibl' => {},
'folldal' => {},
'forde' => {},
'forsand' => {},
'fosnes' => {},
'frana' => {},
'fredrikstad' => {},
'frei' => {},
'frogn' => {},
'froland' => {},
'frosta' => {},
'froya' => {},
'fræna' => {},
'frøya' => {},
'fuoisku' => {},
'fuossko' => {},
'fusa' => {},
'fylkesbibl' => {},
'fyresdal' => {},
'førde' => {},
'gaivuotna' => {},
'galsa' => {},
'gamvik' => {},
'gangaviika' => {},
'gaular' => {},
'gausdal' => {},
'giehtavuoatna' => {},
'gildeskal' => {},
'gildeskål' => {},
'giske' => {},
'gjemnes' => {},
'gjerdrum' => {},
'gjerstad' => {},
'gjesdal' => {},
'gjovik' => {},
'gjøvik' => {},
'gloppen' => {},
'gol' => {},
'gran' => {},
'grane' => {},
'granvin' => {},
'gratangen' => {},
'grimstad' => {},
'grong' => {},
'grue' => {},
'gulen' => {},
'guovdageaidnu' => {},
'gáivuotna' => {},
'gálsá' => {},
'gáŋgaviika' => {},
'ha' => {},
'habmer' => {},
'hadsel' => {},
'hagebostad' => {},
'halden' => {},
'halsa' => {},
'hamar' => {},
'hamaroy' => {},
'hammarfeasta' => {},
'hammerfest' => {},
'hapmir' => {},
'haram' => {},
'hareid' => {},
'harstad' => {},
'hasvik' => {},
'hattfjelldal' => {},
'haugesund' => {},
'hedmark' => {'os' => {},
'valer' => {},
'våler' => {}},
'hemne' => {},
'hemnes' => {},
'hemsedal' => {},
'herad' => {},
'hitra' => {},
'hjartdal' => {},
'hjelmeland' => {},
'hl' => {'gs' => {}},
'hm' => {'gs' => {}},
'hobol' => {},
'hobøl' => {},
'hof' => {},
'hokksund' => {},
'hol' => {},
'hole' => {},
'holmestrand' => {},
'holtalen' => {},
'holtålen' => {},
'honefoss' => {},
'hordaland' => {'os' => {}},
'hornindal' => {},
'horten' => {},
'hoyanger' => {},
'hoylandet' => {},
'hurdal' => {},
'hurum' => {},
'hvaler' => {},
'hyllestad' => {},
'hábmer' => {},
'hámmárfeasta' => {},
'hápmir' => {},
'hå' => {},
'hægebostad' => {},
'hønefoss' => {},
'høyanger' => {},
'høylandet' => {},
'ibestad' => {},
'idrett' => {},
'inderoy' => {},
'inderøy' => {},
'iveland' => {},
'ivgu' => {},
'jan-mayen' => {'gs' => {}},
'jessheim' => {},
'jevnaker' => {},
'jolster' => {},
'jondal' => {},
'jorpeland' => {},
'jølster' => {},
'jørpeland' => {},
'kafjord' => {},
'karasjohka' => {},
'karasjok' => {},
'karlsoy' => {},
'karmoy' => {},
'karmøy' => {},
'kautokeino' => {},
'kirkenes' => {},
'klabu' => {},
'klepp' => {},
'klæbu' => {},
'kommune' => {},
'kongsberg' => {},
'kongsvinger' => {},
'kopervik' => {},
'kraanghke' => {},
'kragero' => {},
'kragerø' => {},
'kristiansand' => {},
'kristiansund' => {},
'krodsherad' => {},
'krokstadelva' => {},
'kråanghke' => {},
'krødsherad' => {},
'kvafjord' => {},
'kvalsund' => {},
'kvam' => {},
'kvanangen' => {},
'kvinesdal' => {},
'kvinnherad' => {},
'kviteseid' => {},
'kvitsoy' => {},
'kvitsøy' => {},
'kvæfjord' => {},
'kvænangen' => {},
'kárášjohka' => {},
'kåfjord' => {},
'laakesvuemie' => {},
'lahppi' => {},
'langevag' => {},
'langevåg' => {},
'lardal' => {},
'larvik' => {},
'lavagis' => {},
'lavangen' => {},
'leangaviika' => {},
'leaŋgaviika' => {},
'lebesby' => {},
'leikanger' => {},
'leirfjord' => {},
'leirvik' => {},
'leka' => {},
'leksvik' => {},
'lenvik' => {},
'lerdal' => {},
'lesja' => {},
'levanger' => {},
'lier' => {},
'lierne' => {},
'lillehammer' => {},
'lillesand' => {},
'lindas' => {},
'lindesnes' => {},
'lindås' => {},
'loabat' => {},
'loabát' => {},
'lodingen' => {},
'lom' => {},
'loppa' => {},
'lorenskog' => {},
'loten' => {},
'lund' => {},
'lunner' => {},
'luroy' => {},
'lurøy' => {},
'luster' => {},
'lyngdal' => {},
'lyngen' => {},
'láhppi' => {},
'lærdal' => {},
'lødingen' => {},
'lørenskog' => {},
'løten' => {},
'malatvuopmi' => {},
'malselv' => {},
'malvik' => {},
'mandal' => {},
'marker' => {},
'marnardal' => {},
'masfjorden' => {},
'masoy' => {},
'matta-varjjat' => {},
'meland' => {},
'meldal' => {},
'melhus' => {},
'meloy' => {},
'meløy' => {},
'meraker' => {},
'meråker' => {},
'midsund' => {},
'midtre-gauldal' => {},
'mil' => {},
'mjondalen' => {},
'mjøndalen' => {},
'mo-i-rana' => {},
'moareke' => {},
'modalen' => {},
'modum' => {},
'molde' => {},
'more-og-romsdal' => {'heroy' => {},
'sande' => {}},
'mosjoen' => {},
'mosjøen' => {},
'moskenes' => {},
'moss' => {},
'mosvik' => {},
'moåreke' => {},
'mr' => {'gs' => {}},
'muosat' => {},
'muosát' => {},
'museum' => {},
'málatvuopmi' => {},
'mátta-várjjat' => {},
'målselv' => {},
'måsøy' => {},
'møre-og-romsdal' => {'herøy' => {},
'sande' => {}},
'naamesjevuemie' => {},
'namdalseid' => {},
'namsos' => {},
'namsskogan' => {},
'nannestad' => {},
'naroy' => {},
'narviika' => {},
'narvik' => {},
'naustdal' => {},
'navuotna' => {},
'nedre-eiker' => {},
'nesna' => {},
'nesodden' => {},
'nesoddtangen' => {},
'nesseby' => {},
'nesset' => {},
'nissedal' => {},
'nittedal' => {},
'nl' => {'gs' => {}},
'nord-aurdal' => {},
'nord-fron' => {},
'nord-odal' => {},
'norddal' => {},
'nordkapp' => {},
'nordland' => {'bo' => {},
'bø' => {},
'heroy' => {},
'herøy' => {}},
'nordre-land' => {},
'nordreisa' => {},
'nore-og-uvdal' => {},
'notodden' => {},
'notteroy' => {},
'nt' => {'gs' => {}},
'návuotna' => {},
'nååmesjevuemie' => {},
'nærøy' => {},
'nøtterøy' => {},
'odda' => {},
'of' => {'gs' => {}},
'oksnes' => {},
'ol' => {'gs' => {}},
'omasvuotna' => {},
'oppdal' => {},
'oppegard' => {},
'oppegård' => {},
'orkanger' => {},
'orkdal' => {},
'orland' => {},
'orskog' => {},
'orsta' => {},
'osen' => {},
'oslo' => {'gs' => {}},
'osoyro' => {},
'osteroy' => {},
'osterøy' => {},
'ostfold' => {'valer' => {}},
'ostre-toten' => {},
'osøyro' => {},
'overhalla' => {},
'ovre-eiker' => {},
'oyer' => {},
'oygarden' => {},
'oystre-slidre' => {},
'porsanger' => {},
'porsangu' => {},
'porsgrunn' => {},
'porsáŋgu' => {},
'priv' => {},
'rade' => {},
'radoy' => {},
'radøy' => {},
'rahkkeravju' => {},
'raholt' => {},
'raisa' => {},
'rakkestad' => {},
'ralingen' => {},
'rana' => {},
'randaberg' => {},
'rauma' => {},
'rendalen' => {},
'rennebu' => {},
'rennesoy' => {},
'rennesøy' => {},
'rindal' => {},
'ringebu' => {},
'ringerike' => {},
'ringsaker' => {},
'risor' => {},
'rissa' => {},
'risør' => {},
'rl' => {'gs' => {}},
'roan' => {},
'rodoy' => {},
'rollag' => {},
'romsa' => {},
'romskog' => {},
'roros' => {},
'rost' => {},
'royken' => {},
'royrvik' => {},
'ruovat' => {},
'rygge' => {},
'ráhkkerávju' => {},
'ráisa' => {},
'råde' => {},
'råholt' => {},
'rælingen' => {},
'rødøy' => {},
'rømskog' => {},
'røros' => {},
'røst' => {},
'røyken' => {},
'røyrvik' => {},
'salangen' => {},
'salat' => {},
'saltdal' => {},
'samnanger' => {},
'sandefjord' => {},
'sandnes' => {},
'sandnessjoen' => {},
'sandnessjøen' => {},
'sandoy' => {},
'sandøy' => {},
'sarpsborg' => {},
'sauda' => {},
'sauherad' => {},
'sel' => {},
'selbu' => {},
'selje' => {},
'seljord' => {},
'sf' => {'gs' => {}},
'siellak' => {},
'sigdal' => {},
'siljan' => {},
'sirdal' => {},
'skanit' => {},
'skanland' => {},
'skaun' => {},
'skedsmo' => {},
'skedsmokorset' => {},
'ski' => {},
'skien' => {},
'skierva' => {},
'skiervá' => {},
'skiptvet' => {},
'skjak' => {},
'skjervoy' => {},
'skjervøy' => {},
'skjåk' => {},
'skodje' => {},
'skánit' => {},
'skånland' => {},
'slattum' => {},
'smola' => {},
'smøla' => {},
'snaase' => {},
'snasa' => {},
'snillfjord' => {},
'snoasa' => {},
'snåase' => {},
'snåsa' => {},
'sogndal' => {},
'sogne' => {},
'sokndal' => {},
'sola' => {},
'solund' => {},
'somna' => {},
'sondre-land' => {},
'songdalen' => {},
'sor-aurdal' => {},
'sor-fron' => {},
'sor-odal' => {},
'sor-varanger' => {},
'sorfold' => {},
'sorreisa' => {},
'sortland' => {},
'sorum' => {},
'spjelkavik' => {},
'spydeberg' => {},
'st' => {'gs' => {}},
'stange' => {},
'stat' => {},
'stathelle' => {},
'stavanger' => {},
'stavern' => {},
'steigen' => {},
'steinkjer' => {},
'stjordal' => {},
'stjordalshalsen' => {},
'stjørdal' => {},
'stjørdalshalsen' => {},
'stokke' => {},
'stor-elvdal' => {},
'stord' => {},
'stordal' => {},
'storfjord' => {},
'strand' => {},
'stranda' => {},
'stryn' => {},
'sula' => {},
'suldal' => {},
'sund' => {},
'sunndal' => {},
'surnadal' => {},
'svalbard' => {'gs' => {}},
'sveio' => {},
'svelvik' => {},
'sykkylven' => {},
'sálat' => {},
'sálát' => {},
'søgne' => {},
'sømna' => {},
'søndre-land' => {},
'sør-aurdal' => {},
'sør-fron' => {},
'sør-odal' => {},
'sør-varanger' => {},
'sørfold' => {},
'sørreisa' => {},
'sørum' => {},
'tana' => {},
'tananger' => {},
'telemark' => {'bo' => {},
'bø' => {}},
'time' => {},
'tingvoll' => {},
'tinn' => {},
'tjeldsund' => {},
'tjome' => {},
'tjøme' => {},
'tm' => {'gs' => {}},
'tokke' => {},
'tolga' => {},
'tonsberg' => {},
'torsken' => {},
'tr' => {'gs' => {}},
'trana' => {},
'tranby' => {},
'tranoy' => {},
'tranøy' => {},
'troandin' => {},
'trogstad' => {},
'tromsa' => {},
'tromso' => {},
'tromsø' => {},
'trondheim' => {},
'trysil' => {},
'træna' => {},
'trøgstad' => {},
'tvedestrand' => {},
'tydal' => {},
'tynset' => {},
'tysfjord' => {},
'tysnes' => {},
'tysvar' => {},
'tysvær' => {},
'tønsberg' => {},
'ullensaker' => {},
'ullensvang' => {},
'ulvik' => {},
'unjarga' => {},
'unjárga' => {},
'utsira' => {},
'va' => {'gs' => {}},
'vaapste' => {},
'vadso' => {},
'vadsø' => {},
'vaga' => {},
'vagan' => {},
'vagsoy' => {},
'vaksdal' => {},
'valle' => {},
'vang' => {},
'vanylven' => {},
'vardo' => {},
'vardø' => {},
'varggat' => {},
'varoy' => {},
'vefsn' => {},
'vega' => {},
'vegarshei' => {},
'vegårshei' => {},
'vennesla' => {},
'verdal' => {},
'verran' => {},
'vestby' => {},
'vestfold' => {'sande' => {}},
'vestnes' => {},
'vestre-slidre' => {},
'vestre-toten' => {},
'vestvagoy' => {},
'vestvågøy' => {},
'vevelstad' => {},
'vf' => {'gs' => {}},
'vgs' => {},
'vik' => {},
'vikna' => {},
'vindafjord' => {},
'voagat' => {},
'volda' => {},
'voss' => {},
'vossevangen' => {},
'várggát' => {},
'vågan' => {},
'vågsøy' => {},
'vågå' => {},
'værøy' => {},
'ákŋoluokta' => {},
'álaheadju' => {},
'áltá' => {},
'åfjord' => {},
'åkrehamn' => {},
'ål' => {},
'ålesund' => {},
'ålgård' => {},
'åmli' => {},
'åmot' => {},
'årdal' => {},
'ås' => {},
'åseral' => {},
'åsnes' => {},
'øksnes' => {},
'ørland' => {},
'ørskog' => {},
'ørsta' => {},
'østfold' => {'våler' => {}},
'østre-toten' => {},
'øvre-eiker' => {},
'øyer' => {},
'øygarden' => {},
'øystre-slidre' => {},
'čáhcesuolo' => {}},
'np' => {'*' => {}},
'nr' => {'biz' => {},
'com' => {},
'edu' => {},
'gov' => {},
'info' => {},
'net' => {},
'org' => {}},
'nu' => {},
'nz' => {'*' => {}},
'om' => {'*' => {}},
'org' => {'ae' => {},
'za' => {}},
'pa' => {'abo' => {},
'ac' => {},
'com' => {},
'edu' => {},
'gob' => {},
'ing' => {},
'med' => {},
'net' => {},
'nom' => {},
'org' => {},
'sld' => {}},
'pe' => {'com' => {},
'edu' => {},
'gob' => {},
'mil' => {},
'net' => {},
'nom' => {},
'org' => {}},
'pf' => {'com' => {},
'edu' => {},
'org' => {}},
'pg' => {'*' => {}},
'ph' => {'com' => {},
'edu' => {},
'gov' => {},
'i' => {},
'mil' => {},
'net' => {},
'ngo' => {},
'org' => {}},
'pk' => {'biz' => {},
'com' => {},
'edu' => {},
'fam' => {},
'gob' => {},
'gok' => {},
'gon' => {},
'gop' => {},
'gos' => {},
'gov' => {},
'info' => {},
'net' => {},
'org' => {},
'web' => {}},
'pl' => {'6bone' => {},
'agro' => {},
'aid' => {},
'art' => {},
'atm' => {},
'augustow' => {},
'auto' => {},
'babia-gora' => {},
'bedzin' => {},
'beskidy' => {},
'bialowieza' => {},
'bialystok' => {},
'bielawa' => {},
'bieszczady' => {},
'biz' => {},
'boleslawiec' => {},
'bydgoszcz' => {},
'bytom' => {},
'cieszyn' => {},
'com' => {},
'czeladz' => {},
'czest' => {},
'dlugoleka' => {},
'edu' => {},
'elblag' => {},
'elk' => {},
'gda' => {},
'gdansk' => {},
'gdynia' => {},
'gliwice' => {},
'glogow' => {},
'gmina' => {},
'gniezno' => {},
'gorlice' => {},
'gov' => {'pa' => {},
'po' => {},
'so' => {},
'sr' => {},
'starostwo' => {},
'ug' => {},
'um' => {},
'upow' => {},
'uw' => {}},
'grajewo' => {},
'gsm' => {},
'ilawa' => {},
'info' => {},
'irc' => {},
'jaworzno' => {},
'jelenia-gora' => {},
'jgora' => {},
'kalisz' => {},
'karpacz' => {},
'kartuzy' => {},
'kaszuby' => {},
'katowice' => {},
'kazimierz-dolny' => {},
'kepno' => {},
'ketrzyn' => {},
'klodzko' => {},
'kobierzyce' => {},
'kolobrzeg' => {},
'konin' => {},
'konskowola' => {},
'krakow' => {},
'kutno' => {},
'lapy' => {},
'lebork' => {},
'legnica' => {},
'lezajsk' => {},
'limanowa' => {},
'lomza' => {},
'lowicz' => {},
'lubin' => {},
'lukow' => {},
'mail' => {},
'malbork' => {},
'malopolska' => {},
'mazowsze' => {},
'mazury' => {},
'mbone' => {},
'med' => {},
'media' => {},
'miasta' => {},
'mielec' => {},
'mielno' => {},
'mil' => {},
'mragowo' => {},
'naklo' => {},
'net' => {},
'ngo' => {},
'nieruchomosci' => {},
'nom' => {},
'nowaruda' => {},
'nysa' => {},
'olawa' => {},
'olecko' => {},
'olkusz' => {},
'olsztyn' => {},
'opoczno' => {},
'opole' => {},
'org' => {},
'ostroda' => {},
'ostroleka' => {},
'ostrowiec' => {},
'ostrowwlkp' => {},
'pc' => {},
'pila' => {},
'pisz' => {},
'podhale' => {},
'podlasie' => {},
'polkowice' => {},
'pomorskie' => {},
'pomorze' => {},
'powiat' => {},
'poznan' => {},
'priv' => {},
'prochowice' => {},
'pruszkow' => {},
'przeworsk' => {},
'pulawy' => {},
'radom' => {},
'rawa-maz' => {},
'realestate' => {},
'rel' => {},
'rybnik' => {},
'rzeszow' => {},
'sanok' => {},
'sejny' => {},
'sex' => {},
'shop' => {},
'siedlce' => {},
'sklep' => {},
'skoczow' => {},
'slask' => {},
'slupsk' => {},
'sopot' => {},
'sos' => {},
'sosnowiec' => {},
'stalowa-wola' => {},
'starachowice' => {},
'stargard' => {},
'suwalki' => {},
'swidnica' => {},
'swiebodzin' => {},
'swinoujscie' => {},
'szczecin' => {},
'szczytno' => {},
'szkola' => {},
'targi' => {},
'tarnobrzeg' => {},
'tgory' => {},
'tm' => {},
'tourism' => {},
'travel' => {},
'turek' => {},
'turystyka' => {},
'tychy' => {},
'usenet' => {},
'ustka' => {},
'walbrzych' => {},
'warmia' => {},
'warszawa' => {},
'waw' => {},
'wegrow' => {},
'wielun' => {},
'wlocl' => {},
'wloclawek' => {},
'wodzislaw' => {},
'wolomin' => {},
'wroc' => {},
'wroclaw' => {},
'zachpomor' => {},
'zagan' => {},
'zakopane' => {},
'zarow' => {},
'zgora' => {},
'zgorzelec' => {}},
'pn' => {'co' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'pr' => {'ac' => {},
'biz' => {},
'com' => {},
'edu' => {},
'est' => {},
'gov' => {},
'info' => {},
'isla' => {},
'name' => {},
'net' => {},
'org' => {},
'pro' => {},
'prof' => {}},
'pro' => {'aca' => {},
'bar' => {},
'cpa' => {},
'eng' => {},
'jur' => {},
'law' => {},
'med' => {}},
'ps' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {},
'plo' => {},
'sec' => {}},
'pt' => {'com' => {},
'edu' => {},
'gov' => {},
'int' => {},
'net' => {},
'nome' => {},
'org' => {},
'publ' => {}},
'pw' => {'belau' => {},
'co' => {},
'ed' => {},
'go' => {},
'ne' => {},
'or' => {}},
'py' => {'*' => {}},
'qa' => {'*' => {}},
're' => {'asso' => {},
'com' => {},
'nom' => {}},
'ro' => {'arts' => {},
'com' => {},
'firm' => {},
'info' => {},
'nom' => {},
'nt' => {},
'org' => {},
'rec' => {},
'store' => {},
'tm' => {},
'www' => {}},
'rs' => {'ac' => {},
'co' => {},
'edu' => {},
'gov' => {},
'in' => {},
'org' => {}},
'ru' => {'ac' => {},
'adygeya' => {},
'altai' => {},
'amur' => {},
'amursk' => {},
'arkhangelsk' => {},
'astrakhan' => {},
'baikal' => {},
'bashkiria' => {},
'belgorod' => {},
'bir' => {},
'bryansk' => {},
'buryatia' => {},
'cbg' => {},
'chel' => {},
'chelyabinsk' => {},
'chita' => {},
'chukotka' => {},
'chuvashia' => {},
'cmw' => {},
'com' => {},
'dagestan' => {},
'dudinka' => {},
'e-burg' => {},
'edu' => {},
'fareast' => {},
'gov' => {},
'grozny' => {},
'int' => {},
'irkutsk' => {},
'ivanovo' => {},
'izhevsk' => {},
'jamal' => {},
'jar' => {},
'joshkar-ola' => {},
'k-uralsk' => {},
'kalmykia' => {},
'kaluga' => {},
'kamchatka' => {},
'karelia' => {},
'kazan' => {},
'kchr' => {},
'kemerovo' => {},
'khabarovsk' => {},
'khakassia' => {},
'khv' => {},
'kirov' => {},
'kms' => {},
'koenig' => {},
'komi' => {},
'kostroma' => {},
'krasnoyarsk' => {},
'kuban' => {},
'kurgan' => {},
'kursk' => {},
'kustanai' => {},
'kuzbass' => {},
'lipetsk' => {},
'magadan' => {},
'magnitka' => {},
'mari' => {},
'mari-el' => {},
'marine' => {},
'mil' => {},
'mordovia' => {},
'mosreg' => {},
'msk' => {},
'murmansk' => {},
'mytis' => {},
'nakhodka' => {},
'nalchik' => {},
'net' => {},
'nkz' => {},
'nnov' => {},
'norilsk' => {},
'nov' => {},
'novosibirsk' => {},
'nsk' => {},
'omsk' => {},
'orenburg' => {},
'org' => {},
'oryol' => {},
'oskol' => {},
'palana' => {},
'penza' => {},
'perm' => {},
'pp' => {},
'pskov' => {},
'ptz' => {},
'pyatigorsk' => {},
'rnd' => {},
'rubtsovsk' => {},
'ryazan' => {},
'sakhalin' => {},
'samara' => {},
'saratov' => {},
'simbirsk' => {},
'smolensk' => {},
'snz' => {},
'spb' => {},
'stavropol' => {},
'stv' => {},
'surgut' => {},
'syzran' => {},
'tambov' => {},
'tatarstan' => {},
'test' => {},
'tom' => {},
'tomsk' => {},
'tsaritsyn' => {},
'tsk' => {},
'tula' => {},
'tuva' => {},
'tver' => {},
'tyumen' => {},
'udm' => {},
'udmurtia' => {},
'ulan-ude' => {},
'vdonsk' => {},
'vladikavkaz' => {},
'vladimir' => {},
'vladivostok' => {},
'volgograd' => {},
'vologda' => {},
'voronezh' => {},
'vrn' => {},
'vyatka' => {},
'yakutia' => {},
'yamal' => {},
'yaroslavl' => {},
'yekaterinburg' => {},
'yuzhno-sakhalinsk' => {},
'zgrad' => {}},
'rw' => {'ac' => {},
'co' => {},
'com' => {},
'edu' => {},
'gouv' => {},
'gov' => {},
'int' => {},
'mil' => {},
'net' => {}},
'sa' => {'com' => {},
'edu' => {},
'gov' => {},
'med' => {},
'net' => {},
'org' => {},
'pub' => {},
'sch' => {}},
'sb' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'sc' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'sd' => {'com' => {},
'edu' => {},
'gov' => {},
'info' => {},
'med' => {},
'net' => {},
'org' => {}},
'se' => {'a' => {},
'ac' => {},
'b' => {},
'bd' => {},
'brand' => {},
'c' => {},
'd' => {},
'e' => {},
'f' => {},
'fh' => {},
'fhsk' => {},
'fhv' => {},
'g' => {},
'h' => {},
'i' => {},
'k' => {},
'komforb' => {},
'kommunalforbund' => {},
'komvux' => {},
'l' => {},
'lanbib' => {},
'm' => {},
'n' => {},
'naturbruksgymn' => {},
'o' => {},
'org' => {},
'p' => {},
'parti' => {},
'pp' => {},
'press' => {},
'r' => {},
's' => {},
'sshn' => {},
't' => {},
'tm' => {},
'u' => {},
'w' => {},
'x' => {},
'y' => {},
'z' => {}},
'sg' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {},
'per' => {}},
'sh' => {},
'si' => {},
'sk' => {},
'sl' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'sm' => {},
'sn' => {'art' => {},
'com' => {},
'edu' => {},
'gouv' => {},
'org' => {},
'perso' => {},
'univ' => {}},
'sr' => {},
'st' => {'co' => {},
'com' => {},
'consulado' => {},
'edu' => {},
'embaixada' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {},
'principe' => {},
'saotome' => {},
'store' => {}},
'su' => {},
'sv' => {'*' => {}},
'sy' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
'sz' => {'ac' => {},
'co' => {},
'org' => {}},
'tc' => {},
'td' => {},
'tel' => {},
'tf' => {},
'tg' => {},
'th' => {'ac' => {},
'co' => {},
'go' => {},
'in' => {},
'mi' => {},
'net' => {},
'or' => {}},
'tj' => {'ac' => {},
'biz' => {},
'co' => {},
'com' => {},
'edu' => {},
'go' => {},
'gov' => {},
'int' => {},
'mil' => {},
'name' => {},
'net' => {},
'nic' => {},
'org' => {},
'test' => {},
'web' => {}},
'tk' => {},
'tl' => {'gov' => {}},
'tm' => {},
'tn' => {'agrinet' => {},
'com' => {},
'defense' => {},
'edunet' => {},
'ens' => {},
'fin' => {},
'gov' => {},
'ind' => {},
'info' => {},
'intl' => {},
'mincom' => {},
'nat' => {},
'net' => {},
'org' => {},
'perso' => {},
'rnrt' => {},
'rns' => {},
'rnu' => {},
'tourism' => {},
'turen' => {}},
'to' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
'tr' => {'*' => {},
'nc' => {'gov' => {}}},
'travel' => {},
'tt' => {'aero' => {},
'biz' => {},
'co' => {},
'com' => {},
'coop' => {},
'edu' => {},
'gov' => {},
'info' => {},
'int' => {},
'jobs' => {},
'mobi' => {},
'museum' => {},
'name' => {},
'net' => {},
'org' => {},
'pro' => {},
'travel' => {}},
'tv' => {},
'tw' => {'club' => {},
'com' => {},
'ebiz' => {},
'edu' => {},
'game' => {},
'gov' => {},
'idv' => {},
'mil' => {},
'net' => {},
'org' => {},
'商業' => {},
'組織' => {},
'網路' => {}},
'tz' => {'ac' => {},
'co' => {},
'go' => {},
'ne' => {},
'or' => {}},
'ua' => {'cherkassy' => {},
'chernigov' => {},
'chernovtsy' => {},
'ck' => {},
'cn' => {},
'com' => {},
'crimea' => {},
'cv' => {},
'dn' => {},
'dnepropetrovsk' => {},
'donetsk' => {},
'dp' => {},
'edu' => {},
'gov' => {},
'if' => {},
'in' => {},
'ivano-frankivsk' => {},
'kh' => {},
'kharkov' => {},
'kherson' => {},
'khmelnitskiy' => {},
'kiev' => {},
'kirovograd' => {},
'km' => {},
'kr' => {},
'ks' => {},
'kv' => {},
'lg' => {},
'lugansk' => {},
'lutsk' => {},
'lviv' => {},
'mk' => {},
'net' => {},
'nikolaev' => {},
'od' => {},
'odessa' => {},
'org' => {},
'pl' => {},
'poltava' => {},
'rovno' => {},
'rv' => {},
'sebastopol' => {},
'sumy' => {},
'te' => {},
'ternopil' => {},
'uzhgorod' => {},
'vinnica' => {},
'vn' => {},
'zaporizhzhe' => {},
'zhitomir' => {},
'zp' => {},
'zt' => {}},
'ug' => {'ac' => {},
'co' => {},
'go' => {},
'ne' => {},
'or' => {},
'sc' => {}},
'uk' => {'*' => {},
'bl' => {'!' => {}},
'british-library' => {'!' => {}},
'icnet' => {'!' => {}},
'jet' => {'!' => {}},
'national-library-scotland' => {'!' => {}},
'nel' => {'!' => {}},
'nhs' => {'!' => {}},
'nls' => {'!' => {}},
'parliament' => {'!' => {}},
'sch' => {'*' => {}}},
'us' => {'ak' => {},
'al' => {},
'ar' => {},
'as' => {},
'az' => {},
'ca' => {},
'co' => {},
'ct' => {},
'dc' => {},
'de' => {},
'dni' => {},
'fed' => {},
'fl' => {},
'ga' => {},
'gu' => {},
'hi' => {},
'ia' => {},
'id' => {},
'il' => {},
'in' => {},
'isa' => {},
'kids' => {},
'ks' => {},
'ky' => {},
'la' => {},
'ma' => {},
'md' => {},
'me' => {},
'mi' => {},
'mn' => {},
'mo' => {},
'ms' => {},
'mt' => {},
'nc' => {},
'nd' => {},
'ne' => {},
'nh' => {},
'nj' => {},
'nm' => {},
'nsn' => {},
'nv' => {},
'ny' => {},
'oh' => {},
'ok' => {},
'or' => {},
'pa' => {},
'pr' => {},
'ri' => {},
'sc' => {},
'sd' => {},
'tn' => {},
'tx' => {},
'ut' => {},
'va' => {},
'vi' => {},
'vt' => {},
'wa' => {},
'wi' => {},
'wv' => {},
'wy' => {}},
'uy' => {'*' => {}},
'uz' => {'co' => {},
'com' => {}},
'va' => {},
'vc' => {'com' => {},
'edu' => {},
'gov' => {},
'mil' => {},
'net' => {},
'org' => {}},
've' => {'*' => {}},
'vg' => {},
'vi' => {'co' => {},
'com' => {},
'k12' => {},
'net' => {},
'org' => {}},
'vn' => {'ac' => {},
'biz' => {},
'com' => {},
'edu' => {},
'gov' => {},
'health' => {},
'info' => {},
'int' => {},
'name' => {},
'net' => {},
'org' => {},
'pro' => {}},
'vu' => {},
'ws' => {'com' => {},
'edu' => {},
'gov' => {},
'net' => {},
'org' => {}},
'ye' => {'*' => {}},
'yu' => {'*' => {}},
'za' => {'*' => {}},
'zm' => {'*' => {}},
'zw' => {'*' => {}},
'рф' => {},
'السعودية' => {},
'امارات' => {},
'مصر' => {}}
end
